runtime: python37

default_expiration: "10s"

handlers:

- url: /js/(.*\.(js))$
  static_files: js/\1
  upload: js/(.*\.(js))$
  expiration: 10s

- url: /images/(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /stylesheets/(.*\.(css))$
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(css))$
  expiration: 10s

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico